### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by JonathanHeyno** [riikkayoki/tsoha-RecipeFinder#31]
- Ulkoasu on erittäin hyvä

- Järjestelmää on helppo käyttää ja selkeä

- Rekisteröintisivulla kannattaisi indikoida (esim. asteriksilla) mitkä kentät ovat pakollisia.

- Miksi keräät pakollisena tietona emailiosoitteeni ja kännykkänumeroni? Mihin aiot käyttää niitä? Mielestäni nämä kentät voisivat olla vapaaehtoisia. Jos ne ovat pakollisia pitäisi mielestäni olla jossain selkeä selostus mihin näitä tietoja käytetään ja miten niitä säilytetään, yms. juridiset selostukset. Ja ketkä kaikki näkevät nämä tiedot? Näkevätkö toiset käyttäjät puhelinnumeroni ja meilini?

- Kännykkänumerokenttään voi laittaa esim. tekstistringin. Se ei varmista että kyseessä on oikeasti numero.

- En tiedä toimiiko CSRF tarkistus oikein. Kun vaihdan login.html tiedostossa CSRF tokenin arvon ja käynnistän ohjelman uudestaan, se antaa logata sisään ilman mitään ongelmia. Käsitttääkseni jos antaa väärän CSRF tokenin arvon sen pitäisi estää pääsemästä eteenpäin. Tai sitten en ymmärrä tätä CSRF hommaa. Itse tein tämän ohjeen mukaisesti: [https://flask-wtf.readthedocs.io/en/0.15.x/csrf/](https://flask-wtf.readthedocs.io/en/0.15.x/csrf/). Käsittääkseni tässä riittää että laittaa app.py tiedostoon:

`from flask_wtf.csrf import CSRFProtect`

`csrf = CSRFProtect(app)`

ja sitten jokaiseen html tideostoon jossa on formi `<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">`

niin sitten se vissiin hoitaa automaagisesti ton CSRF tarkistuksen aina kun tulee POST

- Koodi on erittäin selkeää

**Comment by riikkayoki** [comment]
Kiitoksia mukavasta vertaisarvioinnista ja vinkeistä! 

Ymmärrän huolen tietojen käsittelystä sovelluksessani. Sovellukseen voi kuitenkin laittaa satunnaisen puhelinnumeron ja sähköpostiosoitteen. Tiedot eivät näy muille. Tarkoituksenani on harjoitella näiden tietojen validiointia. Koin myös profiilitietojen keräämisen ja näyttämisen käyttäjän profiilissa hyväksi harjoitukseksi. 

Koska kurssin vaatimuksissa ei vaadita juridisia selostuksia tiedon keräämisestä, ja koska kyseessä on harjoitusprojekti, en valitettavasti ehdi perehtymään aiheeseen kurssin aikarajoitteiden puitteissa. 

Laitan kuitenkin ehdottomasti tuohon rekisteröintilomakkeeseen vielä selvemmäksi mitkä tiedot ovat pakollisia. 

Kiitos
